version: '3.8'
services:
  php-apache-environment:
    container_name: php-teamprojects
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./client/src:/var/www/html/
    ports:
      - 1337:80
  db:
    container_name: mydb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lionPass
      MYSQL_DATABASE: lionDB
      MYSQL_USER: lionUser
      MYSQL_PASSWORD: lionPass
    ports:
      - '9806:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9090:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
